"""Generated from contracts/record_contract.json. Do not edit by hand."""

RECORD_CONTRACT = 'catalyst-data-record/1.0'
RECORD_SCHEMA_URI = 'https://sustainablecatalyst.com/schemas/catalyst-data-record-1.0.json'
EVIDENCE_CONTRACT = 'catalyst-data-evidence-chain/1.0'
EVIDENCE_SCHEMA_URI = 'https://sustainablecatalyst.com/schemas/catalyst-data-evidence-chain-1.0.json'
INDICATOR_GOVERNANCE_CONTRACT = 'catalyst-data-indicator-governance/1.0'
INDICATOR_GOVERNANCE_SCHEMA_URI = 'https://sustainablecatalyst.com/schemas/catalyst-data-indicator-governance-1.0.json'
OBSERVATION_LINEAGE_CONTRACT = 'catalyst-data-observation-lineage/1.0'
OBSERVATION_LINEAGE_SCHEMA_URI = 'https://sustainablecatalyst.com/schemas/catalyst-data-observation-lineage-1.0.json'
REVIEW_WORKFLOW_CONTRACT = 'catalyst-data-review-workflow/1.0'
REVIEW_WORKFLOW_SCHEMA_URI = 'https://sustainablecatalyst.com/schemas/catalyst-data-review-workflow-1.0.json'
RECORD_TYPES = ('measurement',)
ENTITY_TYPES = ('country', 'organization', 'project', 'program', 'site', 'policy', 'persona', 'experiment', 'dataset', 'other')
SOURCE_TYPES = ('internal record', 'third-party dataset', 'survey', 'public registry', 'model estimate', 'publication', 'sensor', 'api', 'other', 'unspecified')
PRODUCER_COMPONENTS = ('python-engine', 'browser-demo', 'migration-tool', 'external', 'import-service', 'repository-service', 'connector-service')
QUALITY_FLAGS = ('estimated', 'incomplete', 'outlier', 'imputed', 'stale', 'conflicting', 'restricted', 'unverified')
EVIDENCE_ROLES = ('primary', 'supporting', 'conflicting', 'derived', 'contextual')
SOURCE_RELATIONSHIPS = ('corroborates', 'conflicts_with', 'derived_from', 'supersedes', 'duplicates', 'contextualizes')
PROVENANCE_EVENT_TYPES = ('record_created', 'record_updated', 'source_versioned', 'source_snapshot_added', 'source_linked', 'source_unlinked', 'transformed', 'reviewed', 'published', 'corrected', 'superseded', 'imported')
EVIDENCE_GAP_SEVERITIES = ('info', 'warning', 'critical')
EVIDENCE_GAP_CODES = ('missing-source', 'missing-citation', 'missing-license', 'missing-retrieval-date', 'missing-checksum', 'missing-method', 'low-confidence', 'conflicting-evidence', 'restricted-source', 'stale-source')
INDICATOR_STATUSES = ('draft', 'active', 'deprecated', 'replaced', 'archived')
INDICATOR_FREQUENCIES = ('continuous', 'daily', 'weekly', 'monthly', 'quarterly', 'annual', 'irregular', 'event', 'custom')
INDICATOR_AGGREGATIONS = ('sum', 'mean', 'median', 'minimum', 'maximum', 'count', 'ratio', 'index', 'point-estimate', 'cumulative', 'custom')
METHODOLOGY_STATUSES = ('draft', 'in-review', 'approved', 'deprecated', 'archived')
FRAMEWORK_MAPPING_RELATIONSHIPS = ('exactMatch', 'closeMatch', 'broaderMatch', 'narrowerMatch', 'relatedMatch')
COMPARABILITY_STATUSES = ('equivalent', 'convertible', 'limited', 'incompatible')
GOVERNANCE_EVENT_TYPES = ('indicator_registered', 'indicator_versioned', 'methodology_versioned', 'unit_registered', 'framework_mapped', 'compatibility_rule_added')
QUESTION_TYPES = ('research', 'decision', 'monitoring', 'evaluation')
QUESTION_STATUSES = ('draft', 'active', 'answered', 'archived')
INSTRUMENT_TYPES = ('survey', 'sensor', 'form', 'api', 'administrative', 'model', 'manual', 'other')
DATASET_ACCESS_LEVELS = ('public', 'internal', 'restricted', 'confidential')
OBSERVATION_ROLES = ('baseline', 'current', 'supporting', 'derived')
OBSERVATION_QUALITY_STATUSES = ('valid', 'missing', 'censored', 'outlier', 'imputed', 'rejected')
LINEAGE_EVENT_TYPES = ('question_linked', 'instrument_versioned', 'dataset_versioned', 'batch_registered', 'observation_recorded', 'observation_linked', 'transformation_recorded')
REVIEW_STATES = ('draft', 'submitted', 'in-review', 'changes-requested', 'approved', 'rejected', 'superseded', 'archived')
REVIEW_PRIORITIES = ('low', 'normal', 'high', 'critical')
REVIEW_DECISION_TYPES = ('submitted', 'review_started', 'changes_requested', 'approved', 'rejected', 'superseded', 'archived', 'reopened', 'quality_assessed', 'publication_gate_updated', 'assigned', 'unassigned', 'commented')
REVIEW_COMMENT_VISIBILITIES = ('internal', 'public')
PUBLICATION_GATE_STATUSES = ('blocked', 'internal', 'external')
QUALITY_DIMENSIONS = ('completeness', 'validity', 'consistency', 'timeliness', 'provenance', 'uncertainty')
LEGACY_CONTRACTS = ('catalyst-data-export/1.0', 'catalyst-data-export/1.0.1', 'unversioned-v1.0.x')
ID_PATTERN = '^[a-z][a-z0-9._:-]{2,255}$'
EXTENSION_KEY_PATTERN = '^[a-z][a-z0-9]*(?:[.-][a-z0-9-]+)+$'
SOURCE_CHECKSUM_PATTERN = '^sha256:[0-9a-f]{64}$'
